### ISSUE TITLE
Update table based on section selected

### ISSUE THREAD

**Issue by hkaspersen** [NorwegianVeterinaryInstitute/cake-planning#4]
Would be nice to have the table as a reactive based on which section is selected in the drop-down menu!

**Comment by novica** [comment]
Filtering should be really just on the table side. Maybe enable the DT fields for filtering on the columns.

However, if there is a cake event in your section for some date and time, and you try to book another one for the same date and time you should get some kind of message saying that cake is already on it's way for that day. :)

What do you think @trishangu? This could be related to #3

**Comment by novica** [comment]
This is resolved in #13
