### ISSUE TITLE
Half hours

### ISSUE THREAD

**Issue by KariHelgesen** [NorwegianVeterinaryInstitute/cake-planning#7]
It would have been nice if it was possible to also invite for cake at half past something.

**Comment by novica** [comment]
@KariHelgesen would you like to try to implement that?

**Comment by KariHelgesen** [comment]
@novica I can try

**Comment by novica** [comment]
The hours are defined here: https://github.com/NorwegianVeterinaryInstitute/cake-planning/blob/a77255637120e2351e3f68d7f0820b4889339283/mod_sidebar.R#L9

It is a simple vector of numbers. You can try changing that to a vector congaing half hours. Either just add the entries in a c() vector or try to generate those with some code like seq(from = , to = , by).

**Comment by trishangu** [comment]
@KariHelgesen you can try for the current version of code. I have made some changes which I will merge soon which will modify this column

**Comment by novica** [comment]
@KariHelgesen apologies. @trishangu  has redone this part. The issue has been resolved with #9
